add_newline = false
format = "${custom.vpn}$all"

[line_break]
disabled = true

[character]
success_symbol = "[](green)"
error_symbol = "[✗](red)"

[directory]
style = "cyan"

[custom.vpn]
when    = " /usr/bin/vpnips " 
command = " /usr/bin/vpnips "
format  = " [ ($output)](yellow) "
