add_newline = false

[python]
symbol = " "

[line_break]
disabled = true

[username]
show_always = true

[character]
symbol = "❯❯"
error_symbol = "✗ "
use_symbol_for_status = true

[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "

[git_branch]
symbol = " "

[java]
symbol = " "

[[battery.display]] 
threshold = 25
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"
