add_newline = false

[python]
symbol = " "

[line_break]
disabled = true

[username]
show_always = true

[character]
symbol = "❯❯"
error_symbol = "✗ "
use_symbol_for_status = true

[[battery.display]] 
threshold = 15
style = "bold red"

[[battery.display]]
threshold = 40
style = "bold yellow"

[cmd_duration]
prefix = "🕙"
