add_newline = false
format = "${custom.vpn}$all"

[line_break]
disabled = true

[character]
success_symbol = "[](green)"
error_symbol = "[✗](red)"

[directory]
style = "cyan"

[custom.vpn]
when    = " ip l show tun0 || ip l show tap0 >/dev/null " 
command = " ip a | grep -e 'inet.*tun\\|inet.*tap' | awk '{print $2}' | cut -d '/' -f 1 | tr '\n' '-' | sed 's/-$//g' "
format  = " [ ($output)](yellow) "
